FROM oven/bun:1.3.12-alpine

WORKDIR /app

RUN apk add --no-cache openssl tzdata

ENV TZ=Asia/Tokyo
ENV NEXT_TELEMETRY_DISABLED=1

COPY package.json bun.lock ./
RUN bun ci

COPY . .
RUN bunx prisma generate

EXPOSE 3000

CMD ["bun", "run", "dev"]
