services:
  app:
    container_name: nextjs_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    # DATABASE_URL: $DATABASE_URL
    ports:
      - "3000:3000" # Expose port 3000 for the Next.js app
    volumes:
      - /app/node_modules # Avoid overwriting `node_modules` in the container
      - .:/app       # Mount the current directory for hot reloading in 
      - /app/.next
    depends_on:
      - postgres
    environment:
      TZ: Asia/Tokyo
      NODE_ENV: development # Set the environment to development
      # CHOKIDAR_USEPOLLING: true
      # CHOKIDAR_INTERVAL: 1000
    command: npm run dev # Use the development server for Next.js

  postgres:
    image: postgres
    restart: always
    container_name: nextjs_postgres
    environment:
      TZ: Asia/Tokyo
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: