version: '3.9'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Expose port 3000 for the Next.js app
    volumes:
      - .:/app       # Mount the current directory for hot reloading in dev
      - /app/node_modules # Avoid overwriting `node_modules` in the container
    environment:
      NODE_ENV: development # Set the environment to development
    command: npm run dev # Use the development server for Next.js
